#!/usr/bin/env bash

# Builds one tool at one revision into a self-contained benchmark binary.
#
# A "tool" is a way of running .emp programs (an interpreter), and it names the
# subject repository it is built from. Several tools can share a subject: both
# 'mata' and 'pymata' are built from 'subjects/mata', the first linking the C++
# library, the second installing that revision's Python bindings.
#
# Each revision of a subject is checked out once into its own git worktree under
# 'build/versions/<subject>/<rev>/src' and every tool builds from there into its
# own directory, so revisions and tools never clobber each other.
#
# Result: bin/<tool>-<rev>
#
# Adding a tool: add it to tool_subject() and write a _build_<tool> function.

set -euo pipefail

die() {
    echo "error: $*" >&2
    exit 1
}

usage() { {
        [ $# -gt 0 ] && echo "error: $1"
        echo "usage: ./scripts/build_version.sh [opts] <tool> <rev> [slug]"
        echo "  <tool>                      tool to build (see --list-tools)"
        echo "  <rev>                       any revision of the tool's subject (tag, branch, commit)"
        echo "  [slug]                      name of the built binary; defaults to <rev>"
        echo "options:"
        echo "  -l|--list-tools             list the known tools and their subjects"
        echo "  -f|--force                  rebuild even if the binary already exists"
        echo "  -b|--build-mode <mode>      Release (default), RelWithDebInfo, Debug"
    } >&2
}

# === Tool registry ===

# Subject repository each tool is built from.
tool_subject() {
    case "$1" in
        mata | pymata) echo "subjects/mata" ;;
        *) return 1 ;;
    esac
}

known_tools() {
    echo "mata pymata"
}

# C++ interpreter linked against libmata of the given revision.
#
# libmata is a static library that also absorbs its 3rd-party objects, so the
# resulting binary contains that revision in full and nothing has to be
# installed system-wide.
_build_mata() {
    local worktree=$1 outdir=$2 binary=$3
    local build="$outdir/mata-build" prefix="$outdir/prefix"
    local harness_build="$outdir/harness-build"
    local harness_src="$rootdir/harnesses/automata-program-parser"

    # Only the library is needed; examples and tests would just cost build time.
    cmake -B "$build" -S "$worktree" \
        -DCMAKE_BUILD_TYPE="$build_mode" \
        -DCMAKE_INSTALL_PREFIX="$prefix" \
        -DBUILD_TESTING:BOOL=OFF \
        -DMATA_BUILD_EXAMPLES:BOOL=OFF
    cmake --build "$build" --parallel "$jobs" --target libmata
    # Installing merges mata's and its 3rd-party headers into a single include
    # directory, which is what the harness' find_path() expects.
    cmake --install "$build" >/dev/null

    echo "======== Building the C++ interpreter ========"
    # CMAKE_PREFIX_PATH makes the harness' find_library()/find_path() resolve to
    # this revision rather than a system-wide or another revision's libmata.
    cmake -B "$harness_build" -S "$harness_src" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="$prefix"
    cmake --build "$harness_build" --parallel "$jobs" --target mata-emp-interpreter
    cp "$harness_build/src/cpp/mata-emp-interpreter" "$binary"
}

# Python interpreter (pyinterpret's MataEngine) on that revision's bindings.
_build_pymata() {
    local worktree=$1 outdir=$2 binary=$3
    local venv="$outdir/venv"
    local pyinterpret_src="$rootdir/harnesses/automata-program-parser/src/python"

    command -v uv >/dev/null || die "uv not found; enter the dev shell or run 'just bootstrap'"
    [ -d "$worktree/bindings/python" ] || die "revision has no Python bindings (bindings/python)"

    rm -rf "$venv"
    # uv's own downloaded CPython is dynamically linked against a generic Linux
    # and does not run on NixOS, so build on the interpreter from the shell.
    uv venv "$venv" --python "$(command -v python3)" >/dev/null
    VIRTUAL_ENV="$venv" uv pip install "$worktree/bindings/python"
    # --no-deps keeps the just-built libmata: pyinterpret depends on
    # 'libmata>=1.0.0' and older revisions would be replaced from PyPI.
    VIRTUAL_ENV="$venv" uv pip install --no-deps "$pyinterpret_src"
    VIRTUAL_ENV="$venv" uv pip install automata-lib fado

    # Wrapper so that every tool is invoked uniformly as '<binary> <prog.emp> <args>'.
    cat > "$binary" <<EOF
#!/usr/bin/env bash
# Generated by scripts/build_version.sh -- pyinterpret on mata's bindings.
exec "$venv/bin/pyinterpret" MataEngine "\$@"
EOF
    chmod +x "$binary"
}

# === Main ===

force=false
build_mode="Release"
args=()
while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            usage
            exit 0;;
        -l|--list-tools)
            for t in $(known_tools); do
                printf '%-10s %s\n' "$t" "$(tool_subject "$t")"
            done
            exit 0;;
        -f|--force)
            force=true
            shift 1;;
        -b|--build-mode)
            build_mode="$2"
            shift 2;;
        -*)
            usage "unknown option: $1"
            exit 1;;
        *)
            args+=( "$1" )
            shift 1;;
    esac
done

[ ${#args[@]} -ge 2 ] || { usage "missing tool or revision"; exit 1; }
tool="${args[0]}"
rev="${args[1]}"
slug="${args[2]:-$rev}"
# '/' would turn branch names such as 'origin/devel' into directories
slug="${slug//\//-}"

subject=$(tool_subject "$tool") || die "unknown tool '$tool' (known: $(known_tools))"

rootdir=$(cd "$(dirname "$0")/.." && pwd)
subject_name=$(basename "$subject")
subject_abs="$rootdir/$subject"
jobs="${JOBS:-$(nproc 2>/dev/null || echo 4)}"

version_dir="$rootdir/build/versions/$subject_name/$slug"
worktree="$version_dir/src"
outdir="$version_dir/$tool"
binary="$rootdir/bin/$tool-$slug"

[ -e "$subject_abs/.git" ] || die "$subject not initialised; run 'git submodule update --init --recursive'"

commit=$(git -C "$subject_abs" rev-parse --verify --quiet "$rev^{commit}") ||
    die "$subject: unknown revision '$rev'"

if [ -x "$binary" ] && [ "$force" = false ]; then
    echo "[!] $tool/$slug: already built ($binary); use --force to rebuild"
    exit 0
fi

echo "========== Building $tool '$slug' ($commit) =========="
mkdir -p "$outdir" "$rootdir/bin"

# One checkout per revision, shared by every tool built from this subject.
if [ -e "$worktree/.git" ]; then
    git -C "$worktree" checkout --detach --force "$commit"
else
    git -C "$subject_abs" worktree prune
    git -C "$subject_abs" worktree add --detach "$worktree" "$commit"
fi

"_build_$tool" "$worktree" "$outdir" "$binary"

echo "$commit" > "$version_dir/COMMIT"
echo "[done] $binary ($(git -C "$worktree" describe --tags --always))"
