#!/usr/bin/env bash

# Benchmarks multiple revisions of a tool against each other.
#
# Each revision is built into its own interpreter binary (see
# scripts/build_version.sh) and then registered as a separate pycobench
# "method", so a single run measures all of them on exactly the same inputs.
# The resulting .csv has one group of columns per revision, and pycobench's
# comparison table (averages, medians, timeouts) is printed at the end.
#
# Supports any combination of commits, tags, and branches from a single
# subjects/ repo.
#
# Example:
#   ./scripts/compare_versions.sh \
#       --subject subjects/mata \
#       --program emp-programs/determinize-minimize.emp \
#       --input inputs/bench-regexps_union.input \
#       v1.32.32 devel origin/master

set -euo pipefail

die() {
    echo "error: $*" >&2
    exit 1
}

usage() { {
        [ $# -gt 0 ] && echo "error: $1"
        echo "usage: ./scripts/compare_versions.sh [opts] <rev1> <rev2> [...revn]"
        echo "options:"
        echo "  -s|--subject <path>         path to subject repo [default=subjects/mata]"
        echo "  -p|--program <prog.emp>     program to run [default=emp-programs/determinize-minimize.emp]"
        echo "  -i|--input <bench.input>    inputs to run on [default=inputs/bench-regexps_union.input]"
        echo "  -t|--timeout <int>          timeout per benchmark in seconds [default=60]"
        echo "  -j|--jobs <int>             number of parallel jobs [default=6]"
        echo "  -o|--output-dir <dir>       store results in 'results/data/<dir>'"
        echo "  -f|--force                  rebuild interpreters even if they exist"
        echo "  -d|--test-run               only run the first input (quick pipeline check)"
    } >&2
}

subject="subjects/mata"
program="emp-programs/determinize-minimize.emp"
input="inputs/bench-regexps_union.input"
timeout=60
jobs=6
output_dir=""
force=""
testrun=""
revs=()

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            usage
            exit 0;;
        -s|--subject)
            subject="$2"
            shift 2;;
        -p|--program)
            program="$2"
            shift 2;;
        -i|--input)
            input="$2"
            shift 2;;
        -t|--timeout)
            timeout="$2"
            shift 2;;
        -j|--jobs)
            jobs="$2"
            shift 2;;
        -o|--output-dir)
            output_dir="$2"
            shift 2;;
        -f|--force)
            force="--force"
            shift 1;;
        -d|--test-run)
            testrun="--test-run"
            shift 1;;
        -*)
            usage "unknown option: $1"
            exit 1;;
        *)
            revs+=( "$1" )
            shift 1;;
    esac
done

[ ${#revs[@]} -ge 2 ] || { usage "need at least two revisions to compare"; exit 1; }

rootdir=$(cd "$(dirname "$0")/.." && pwd)
cd "$rootdir"

# Validate all revisions exist first, before building any.
# This catches typos and missing branches early.
subject_abs=$(realpath "$subject" 2>/dev/null) ||
    die "subject repo not found: $subject"
[ -e "$subject_abs/.git" ] || die "subject is not a git repository: $subject"

echo "[!] Validating revisions in $subject..."
for rev in "${revs[@]}"; do
    if ! git -C "$subject_abs" rev-parse --verify --quiet "$rev^{commit}" >/dev/null 2>&1; then
        die "$subject: unknown revision '$rev' (try 'git -C $subject fetch --all --tags')"
    fi
done
echo "[✓] All revisions valid"

# Validate program and input exist.
program=$(realpath --relative-to="$rootdir" "$program") || die "no such program: $program"
input=$(realpath --relative-to="$rootdir" "$input") || die "no such input file: $input"
[ -f "$program" ] || die "no such program: $program"
[ -f "$input" ] || die "no such input file: $input"

# Build each revision.
subject_name=$(basename "$subject")
slugs=()
for rev in "${revs[@]}"; do
    ./scripts/build_version.sh ${force:+"$force"} "$subject" "$rev"
    slugs+=( "${rev//\//-}" )
done

# Inputs are ';'-delimited; each column becomes one argument of the program.
params=$(( $(head -1 < "$input" | tr -cd ';' | wc -c) + 1 ))
args=""
for i in $(seq 1 "$params"); do
    args+=" \$$i"
done

# Generate pycobench config with one method per revision.
config_dir="jobs/generated"
config="$config_dir/${subject_name}-versions-$(basename "${program%.*}").yaml"
mkdir -p "$config_dir"
{
    echo "# Generated by scripts/compare_versions.sh -- regenerate, do not edit"
    echo "# subject:  $subject"
    echo "# program:  $program"
    echo "# inputs:   $input"
    for slug in "${slugs[@]}"; do
        echo
        echo "${subject_name}-$slug:"
        echo "  cmd: ./bin/emp-interpreter-${subject_name}-$slug ./$program$args"
    done
} > "$config"

echo "[!] Comparing ${#slugs[@]} revisions: ${slugs[*]}"
echo "[!] Job config: $config"
exec bash ./scripts/run_pyco.sh $testrun --config "$config" --timeout "$timeout" --jobs "$jobs" \
    ${output_dir:+-s "$output_dir"} "$input"
